trigger:
- main

pool:
  name: devops  # your self-hosted pool name

variables:
  ACR_NAME: 'myacrname123'        # Replace with your ACR name
  IMAGE_NAME: 'myapp'
  IMAGE_TAG: '$(Build.BuildId)'

steps:
- script: |
    echo "Logging into Azure..."
    az login --service-principal \
      --username $(AZURE_CLIENT_ID) \
      --password $(AZURE_CLIENT_SECRET) \
      --tenant $(AZURE_TENANT_ID)

    echo "Logging into ACR..."
    az acr login --name $(ACR_NAME)

    echo "Building Docker image..."
    docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG) .

    echo "Pushing Docker image to ACR..."
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)
  displayName: 'Docker Build & Push'
